// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	GetAllCorr(ctx context.Context) ([]Corrpair, error)
	GetAllDate(ctx context.Context) ([]string, error)
	GetAllParam(ctx context.Context) ([]Modelparameter, error)
	GetAllStats(ctx context.Context) ([]Statistic, error)
	GetCorr(ctx context.Context, date string) ([]Corrpair, error)
	GetLatestCorrDate(ctx context.Context) (string, error)
	GetLatestParamDate(ctx context.Context) (string, error)
	GetLatestPrice(ctx context.Context) ([]GetLatestPriceRow, error)
	GetLatestStatsDate(ctx context.Context) (string, error)
	GetParam(ctx context.Context, date string) ([]Modelparameter, error)
	GetStats(ctx context.Context, date string) ([]Statistic, error)
	GetUser(ctx context.Context, prefix string) (User, error)
	InsertCorr(ctx context.Context, arg InsertCorrParams) (Corrpair, error)
	InsertParam(ctx context.Context, arg InsertParamParams) (Modelparameter, error)
	InsertStat(ctx context.Context, arg InsertStatParams) (Statistic, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
